[project]
name = "skillet"
version = "0.0.2"
description = "A Robot Skills framework for manipulation tasks with integration for ROS2 and IsaacLab"
requires-python = ">= 3.10"
authors = [
    {name = "Jeff Jewett", email = "jewettje@oregonstate.edu"},
    {name = "Will Solow", email = "soloww@oregonstate.edu"},
]
license = "MIT"
license-files = ["LICENSE.txt"]
homepage = "https://github.com/Intelligent-Reliable-Autonomous-Systems/Robot-Skills"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "torch",
    "numpy",
    "gymnasium>=1.1",
    "jaxtyping",
    "pyrealsense2",
    "typing-extensions",
    "pynput",
    "tensordict",
    "scipy",
]

[project.optional-dependencies]
planning = [
    "unified_planning",
    "unified-planning[pyperplan,tamer,fast-downward]"
]
vla = [
    "transformers",
    "timm",
    "torchvision",
]
perception = [
    "open3d",
    "pupil-apriltags",
    "google-genai",
    "opencv-python",
    "psutil",
    "h5py",
    "uvicorn",
    "fastapi",
    "python-multipart"
]
ros = [
    "roslibpy",
]
kortex = [
    "pin",
    "protobuf==7.34.1"
]
isaac = [
    "isaacsim[all,extscache]==5.1.0",
    "isaaclab"
]
mujoco = [
    "mujoco",
    "mujoco-warp",
    "mjlab",
    "hydra-core"
]
dev = [
    "ruff",
    "mypy",
    "pytest",
]

[project.scripts]
mj_train = "skillet.scripts.rl.mj_train:main"
isaac_train = "skillet.scripts.rl.isaac_train:main"
ros2_train = "skillet.scripts.rl.ros2_train:main"
mj_play = "skillet.scripts.rl.mj_play:main"
isaac_play = "skillet.scripts.rl.isaac_play:main"
ros2_play = "skillet.scripts.rl.ros2_play:main"
ros2_teleop = "skillet.scripts.teleop.ros2_teleop:main"
sam3_server = "skillet.perception.segmentation.sam.sam_base:main"
vla_server = "skillet.policy.vla:main"


#[project.entry-points."gymnasium.envs"]

[build-system]
requires = ["hatchling", "swig"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["skillet"]

[tool.ruff.lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and isort (`I`) codes
select = [
    "ANN",       # flake8-annotations: Enforces function type hints
    "D",         # pydocstyle: Enforces docstring format (helps with type hints)
    "E", "W",    # pycodestyle: Standard PEP 8 errors & warnings
    "F",         # Pyflakes: Detects undefined variables, unused imports, etc.
    "FA",        # flake8-future-annotations: Encourages `from __future__ import annotations`
    "B",         # flake8-bugbear: Finds likely bugs & design issues
    "SIM",       # flake8-simplify: Simplifies redundant expressions
    "TC",        # flake8-type-checking: Encourages proper `TYPE_CHECKING` usage
    "PERF",      # Perflint: Performance optimizations
    "UP",        # pyupgrade: Keeps syntax modern
    "RUF",       # Ruff-specific improvements
    "C4",        # flake8-comprehensions: Optimize list/set comprehensions
    "RET",       # flake8-return: Enforces consistent return statements
    "ARG",       # flake8-unused-arguments: Flags unused function arguments
    "PTH",       # flake8-use-pathlib: Encourages `pathlib` over `os.path`
    "ISC",       # flake8-implicit-str-concat: Catches unintended string concatenation
    "ICN",       # flake8-import-conventions: Enforces import naming conventions
    "I",         # isort: Automatically sorts imports
    "TRY",       # tryceratops: Improves exception handling
    "N",         # pep8-naming: Enforces naming conventions
]
preview = true
explicit-preview-rules = true

ignore = [
    "ARG001",  # Allow unused arguments
    "ARG002",  # Allow unused method args
    "ARG005",  # Allow unused lambda arguments
    "D203",    # Require blank line before class docstring
    "D213",    # Summary line on second line of docstring
    "TRY003",  # Allow long exception messages
    "F722",    # Allow certain forward references like "b ..." in Shaped[np.ndarray, "b ..."]
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff]
line-length = 120

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",

    "cfg",
]

[tool.ruff.lint.per-file-ignores]
"examples/*" = ["E402"]
"main_isaac.py" = ["ALL"]
[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"  # Enforce double quotes for strings
multiline-quotes = "double"  # Enforce double quotes for multiline strings
docstring-quotes = "double"  # Enforce double quotes for docstrings

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["."]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
exclude = [
    "cfg"
]