(:objects light_pink_block green_block dark_red_block yellow_block - block table0 - table)
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block green_block table0))
(:state (on light_pink_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block yellow_block))
(:state (on green_block yellow_block) (on light_pink_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block light_pink_block table0))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block green_block))
(:state (on green_block yellow_block) (on light_pink_block green_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block light_pink_block green_block))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block green_block))
(:state (on green_block yellow_block) (on light_pink_block green_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block dark_red_block table0))
(:state (on green_block yellow_block) (on light_pink_block green_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block light_pink_block green_block))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block dark_red_block))
(:state (on green_block yellow_block) (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block light_pink_block dark_red_block))
(:state (on green_block yellow_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block dark_red_block))
(:state (on green_block yellow_block) (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block green_block yellow_block))
(:state (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block yellow_block))
(:state (on green_block yellow_block) (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block green_block yellow_block))
(:state (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block table0))
(:state (on green_block table0) (on light_pink_block dark_red_block) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ))
(:action (pick-block light_pink_block dark_red_block))
(:state (on green_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block dark_red_block))
(:state (on green_block table0) (on yellow_block table0) (on dark_red_block table0) (clear table0) (clear green_block) (clear light_pink_block) (clear yellow_block) (clear dark_red_block) (small green_block) (small light_pink_block) (small yellow_block) (small dark_red_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block dark_red_block))
