from .discard import DiscardSkill as DiscardSkill
from .drag_block import DragBlock2Skill as DragBlock2Skill
from .drag_block import DragBlock5Skill as DragBlock5Skill
from .drag_block import DragBlockSkill as DragBlockSkill
from .pick_block import PickBlock2Skill as PickBlock2Skill
from .pick_block import PickBlockSkill as PickBlockSkill
from .place_block import PlaceBlock2Skill as PlaceBlock2Skill
from .place_block import PlaceBlock4Skill as PlaceBlock4Skill
from .place_block import PlaceBlockSkill as PlaceBlockSkill
from .place_table import PlaceTableSkill as PlaceTableSkill
from .rotate_block import RotateBlockSkill as RotateBlockSkill
