(:objects green_block light_blue_block yellow_block light_pink_block - block table0 - table)
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block table0))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block yellow_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block green_block table0))
(:state (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block table0))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block green_block table0))
(:state (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block green_block))
(:state (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping green_block))
(:action (place-block green_block table0))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block light_blue_block) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block light_blue_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block yellow_block))
(:state (on green_block table0) (on light_pink_block table0) (on light_blue_block light_pink_block) (clear table0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block green_block))
(:state (on green_block table0) (on light_pink_block table0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ))
(:action (pick-block yellow_block green_block))
