(:objects yellow_block green_block light_pink_block light_blue_block - block table_0 - table)
(:state (on green_block table_0) (on light_pink_block table_0) (on yellow_block table_0) (on light_blue_block light_pink_block) (clear table_0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block yellow_block table_0))
(:state (on green_block table_0) (on light_pink_block table_0) (on light_blue_block light_pink_block) (clear table_0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block green_block))
(:state (on green_block table_0) (on light_pink_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block yellow_block green_block))
(:state (on green_block table_0) (on light_pink_block table_0) (on light_blue_block light_pink_block) (clear table_0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block yellow_block))
(:state (on green_block table_0) (on light_pink_block table_0) (on light_blue_block light_pink_block) (clear table_0) (clear green_block) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping yellow_block))
(:action (place-block yellow_block green_block))
(:state (on green_block table_0) (on light_pink_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block yellow_block))
(:state (on green_block table_0) (on light_pink_block yellow_block) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block yellow_block))
(:state (on green_block table_0) (on light_pink_block yellow_block) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block table_0))
(:state (on green_block table_0) (on light_pink_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block light_blue_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block light_blue_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block light_blue_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block table_0))
(:state (on green_block table_0) (on light_pink_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block light_blue_block))
(:state (on green_block table_0) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear yellow_block) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_blue_block))
(:action (place-block light_blue_block yellow_block))
(:state (on green_block table_0) (on light_pink_block yellow_block) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
(:state (on green_block table_0) (on light_pink_block yellow_block) (on yellow_block green_block) (on light_blue_block light_pink_block) (clear table_0) (clear light_blue_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_blue_block light_pink_block))
