(:objects green_block light_blue_block yellow_block light_pink_block - block table_0 - table)
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (on light_blue_block table_0) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_pink_block light_blue_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block yellow_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (on light_blue_block yellow_block) (clear table_0) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_pink_block light_blue_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block yellow_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (on light_blue_block yellow_block) (clear table_0) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_pink_block light_blue_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block light_pink_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (clear table_0) (clear light_pink_block) (clear yellow_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block) (gripper-full ) (grasping light_pink_block))
(:action (place-block light_pink_block yellow_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (on light_blue_block yellow_block) (clear table_0) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_pink_block light_blue_block))
(:state (on green_block table_0) (on light_pink_block light_blue_block) (on yellow_block green_block) (on light_blue_block yellow_block) (clear table_0) (clear light_pink_block) (small green_block) (small light_pink_block) (small yellow_block) (small light_blue_block))
(:action (pick-block light_pink_block light_blue_block))
